version: '3.4'

services:
  usermanager:
    image: ${DOCKER_REGISTRY-}usermanager
    build:
      context: .
      dockerfile: UserManager/Dockerfile.test
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1