FROM alpine:3.15.2 AS base

RUN apk add --no-cache \ 
    openssh libunwind \
    nghttp2-libs libidn krb5-libs libuuid lttng-ust zlib \
    libstdc++ libintl \
    icu libstdc++

WORKDIR /app

EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["UserManager/UserManager.csproj", "UserManager/"]
RUN dotnet restore "UserManager/UserManager.csproj"
COPY . .
WORKDIR "/src/UserManager"
RUN dotnet build "UserManager.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "UserManager.csproj" --runtime alpine-x64 --self-contained true -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["./UserManager", "--urls", "http://0.0.0.0:80"]